/* Generated by:Nitin kumar
   Inst. Name:  ASET BIJWASEN
*/
#include <bits/stdc++.h>

using namespace std;

int main()
{
    int m,n;
    cin>>m>>n;
    cout<<((m%2)*n+(n%2)*m+1)/2+(m-m%2)*(n-n%2)/4;
    return 0;
}
